table Report_Source
	lineageTag: 8c0a7ba1-662d-434c-a9b7-1a81c993d199

	column Report
		dataType: string
		lineageTag: 369a58d0-95ed-44a1-ba4a-8b980f4e2468
		summarizeBy: none
		sourceColumn: Report

		annotation SummarizationSetBy = Automatic

	column Field
		dataType: string
		lineageTag: be3edec7-73c9-436b-8f2d-eb156e0ba60e
		summarizeBy: none
		sourceColumn: Field

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 251ff027-8180-43b4-b81f-895c769ad935
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column Scope
		dataType: string
		lineageTag: b9ca547c-6dfd-4733-b51f-1b5c5a786a65
		summarizeBy: none
		sourceColumn: Scope

		annotation SummarizationSetBy = Automatic

	column 'Update frequency'
		dataType: string
		lineageTag: b996518f-d81a-4fc2-8822-5bae7054da4a
		summarizeBy: none
		sourceColumn: Update frequency

		annotation SummarizationSetBy = Automatic

	partition Report_Source = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://iweof.sharepoint.com/teams/o365g_businessintelligencegroupprocurement_imssemal", [ApiVersion = 15]),
				    FilteredRows_Folder = Table.SelectRows(Source, each Text.Contains([Folder Path], "https://iweof.sharepoint.com/teams/o365g_businessintelligencegroupprocurement_imssemal/Shared Documents/General/06 Team working folders/08 P2P KPIs and reports/02 - Power BI files/Information Pages/")),
				    Navigation = FilteredRows_Folder{[Name="Information page.xlsx",#"Folder Path"="https://iweof.sharepoint.com/teams/o365g_businessintelligencegroupprocurement_imssemal/Shared Documents/General/06 Team working folders/08 P2P KPIs and reports/02 - Power BI files/Information Pages/"]}[Content],
				    ImportedExcel = Excel.Workbook(Navigation,true),
				    ReportSourceSheet = ImportedExcel{[Item="Report Source",Kind="Sheet"]}[Data],
				    RemovedOtherColumns = Table.SelectColumns(ReportSourceSheet,{"Report", "Field", "Source", "Scope", "Update frequency"})
				in
				    RemovedOtherColumns

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

